# Generated by Django 3.0.7 on 2020-06-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(blank=True, to='demo.Publication'),
        ),
    ]
